import { AdminError } from './errors.js';
import { writeAuditEvent } from './audit.js';
import { assertUploadTransition } from './upload-state.js';

const rowToJob=row=>row&&({jobId:row.job_id,actorDiscordId:row.actor_discord_id,proposedAssetId:row.proposed_asset_id,baseCommitSha:row.base_commit_sha,publicId:row.cloudinary_public_id,version:row.cloudinary_version,status:row.status,format:row.format,bytes:row.byte_size,width:row.width,height:row.height,animated:Boolean(row.animated),mutation:row.mutation_json?JSON.parse(row.mutation_json):null,mutationHash:row.mutation_sha256,idempotencyKey:row.idempotency_key,requestHash:row.request_sha256,finalizeKey:row.finalize_idempotency_key,finalizeHash:row.finalize_sha256,retryKey:row.retry_idempotency_key,retryHash:row.retry_sha256,commitSha:row.catalog_commit_sha,catalogDigest:row.catalog_digest,failureCode:row.failure_code,recoverable:Boolean(row.recoverable),cleanupState:row.cleanup_state,createdAt:row.created_at,updatedAt:row.updated_at,expiresAt:row.expires_at});
export function uploadStore({env={},data={}}={}){if(data.uploadStore)return data.uploadStore;const db=env.ADMIN_DB;if(!db?.prepare)return null;return {
  async find(actor,key){return rowToJob(await db.prepare('SELECT * FROM upload_jobs WHERE actor_discord_id = ? AND idempotency_key = ? LIMIT 1').bind(actor,key).first());},async get(id){return rowToJob(await db.prepare('SELECT * FROM upload_jobs WHERE job_id = ? LIMIT 1').bind(id).first());},async findByCommit(sha){return rowToJob(await db.prepare('SELECT * FROM upload_jobs WHERE catalog_commit_sha = ? LIMIT 1').bind(sha).first());},async activeAssetIds(){const result=await db.prepare("SELECT proposed_asset_id FROM upload_jobs WHERE status NOT IN ('failed','expired','cleaned')").all();return (result.results||[]).map(r=>r.proposed_asset_id);},
  async create(v){await db.prepare('INSERT INTO upload_jobs (job_id,actor_discord_id,proposed_asset_id,base_commit_sha,cloudinary_public_id,status,mutation_json,mutation_sha256,idempotency_key,request_sha256,recoverable,created_at,updated_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,0,?,?,?)').bind(v.jobId,v.actorDiscordId,v.proposedAssetId,v.baseCommitSha,v.publicId,v.status,JSON.stringify(v.mutation),v.mutationHash,v.idempotencyKey,v.requestHash,v.createdAt,v.createdAt,v.expiresAt).run();return v;},
  async update(id,patch){const current=await this.get(id);if(!current)throw new AdminError(404,'upload_job_not_found','The upload job was not found.');if(patch.status)assertUploadTransition(current.status,patch.status);const next={...current,...patch};await db.prepare('UPDATE upload_jobs SET status=?,base_commit_sha=?,cloudinary_asset_id=?,cloudinary_version=?,cloudinary_resource_type=?,cloudinary_delivery_type=?,format=?,byte_size=?,width=?,height=?,animated=?,mutation_json=?,mutation_sha256=?,finalize_idempotency_key=?,finalize_sha256=?,retry_idempotency_key=?,retry_sha256=?,catalog_commit_sha=?,catalog_digest=?,failure_code=?,sanitized_failure=?,recoverable=?,cleanup_state=?,updated_at=? WHERE job_id=?').bind(next.status,next.baseCommitSha,next.cloudinaryAssetId||null,next.version||null,next.resourceType||null,next.deliveryType||null,next.format||null,next.bytes||null,next.width||null,next.height||null,next.animated==null?null:Number(next.animated),JSON.stringify(next.mutation),next.mutationHash||null,next.finalizeKey||null,next.finalizeHash||null,next.retryKey||null,next.retryHash||null,next.commitSha||null,next.catalogDigest||null,next.failureCode||null,next.sanitizedFailure||null,Number(Boolean(next.recoverable)),next.cleanupState||'not_eligible',next.updatedAt,id).run();return next;},async audit(event,now){await writeAuditEvent(db,event,now);}
};}
export function requireUploadStore(context){const store=uploadStore(context);if(!store)throw new AdminError(503,'admin_database_unavailable','Administration is temporarily unavailable.');return store;}
export function createMemoryUploadStore(){const values=[];const audits=[];return {values,audits,async find(actor,key){return values.find(v=>v.actorDiscordId===actor&&v.idempotencyKey===key)||null;},async get(id){return values.find(v=>v.jobId===id)||null;},async findByCommit(sha){return values.find(v=>v.commitSha===sha)||null;},async activeAssetIds(){return values.filter(v=>!['failed','expired','cleaned'].includes(v.status)).map(v=>v.proposedAssetId);},async create(v){if(values.some(x=>x.proposedAssetId===v.proposedAssetId&&!['failed','expired','cleaned'].includes(x.status)))throw new AdminError(409,'asset_id_reserved','The asset ID is already reserved.');values.push(structuredClone(v));return v;},async update(id,patch){const v=values.find(x=>x.jobId===id);if(!v)throw new AdminError(404,'upload_job_not_found','The upload job was not found.');if(patch.status)assertUploadTransition(v.status,patch.status);Object.assign(v,structuredClone(patch));return structuredClone(v);},async audit(e){audits.push(structuredClone(e));}};}
