let state; let original; let tab = 'categories'; let selectedId = null; let visibleAssets = [];
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
const nextId = (items, prefix) => { const max = Math.max(0, ...items.map(item => new RegExp(`^${prefix}-(\\d+)$`).exec(item.id)?.[1]).filter(Boolean).map(Number)); return `${prefix}-${String(max + 1).padStart(3, '0')}`; };
const current = () => state?.[tab].find(item => item.id === selectedId);
const notice = text => { const node = $('#status'); node.textContent = text; node.style.display = 'block'; setTimeout(() => node.style.display = 'none', 2600); };
const collectionAssets = (collection, source = state) => collection ? source.assets.filter(asset => asset.collectionSlugs.includes(collection.slug)) : [];
function categoryAssets(category, source = state) {
  const filter = category?.filter; if (!filter) return [];
  if (filter.type === 'folder') return source.assets.filter(asset => asset.category === filter.category);
  if (filter.type === 'tags') return source.assets.filter(asset => filter.tags.every(tag => asset.tags.includes(tag)));
  if (filter.type === 'assets') { const byId = new Map(source.assets.map(asset => [asset.id, asset])); return [...new Set(filter.assetIds)].map(id => byId.get(id)).filter(Boolean); }
  if (filter.type === 'collection') { const collection = source.collections.find(item => item.id === filter.collectionId); return collectionAssets(collection, source); }
  return [];
}
const selectedIds = item => new Set(tab === 'collections' ? collectionAssets(item).map(asset => asset.id) : categoryAssets(item).map(asset => asset.id));

async function load() { const response = await fetch('/api/state'); state = await response.json(); original = structuredClone(state); selectedId = state[tab][0]?.id || null; render(); }
function render() { renderRecords(); renderEditor(); renderAssets(); $('#create').textContent = `Create ${tab === 'categories' ? 'category' : 'collection'}`; }
function renderRecords() { $('#records').innerHTML = state[tab].map(item => `<button class="record ${item.id === selectedId ? 'active' : ''}" data-id="${esc(item.id)}"><strong>${esc(item.title)}</strong><small>${esc(item.slug)} · ${esc(item.id)}</small></button>`).join(''); document.querySelectorAll('.record').forEach(button => button.onclick = () => { selectedId = button.dataset.id; render(); }); }
const input = (label, name, value, type = 'text') => `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}"></label>`;
function renderEditor() {
  const item = current(); $('#empty').hidden = Boolean(item); const form = $('#editor'); form.hidden = !item; if (!item) return;
  if (tab === 'categories') {
    const filter = item.filter || { type: 'assets', assetIds: [] }; const filterValue = filter.type === 'assets' ? '<p>Select explicit assets in the picker.</p>' : input(filter.type === 'collection' ? 'Collection stable ID' : 'Filter value', 'filterValue', filter.category || filter.tags?.join(', ') || filter.collectionId || '');
    form.innerHTML = `${input('Stable ID', 'id', item.id)}${input('Slug', 'slug', item.slug)}${input('Display title', 'title', item.title)}<label>Description<textarea name="description">${esc(item.description || '')}</textarea></label><div class="row"><div class="count-card"><span>Matching assets</span><strong id="editor-count">${categoryAssets(item).length}</strong><span id="editor-detail">Filter: ${esc(filter.type)}</span></div>${input('Order', 'order', item.order ?? 0, 'number')}</div><label><input name="visible" type="checkbox" ${item.visible ? 'checked' : ''}> Visible</label><label>Filter type<select name="filterType"><option value="assets" ${filter.type === 'assets' ? 'selected' : ''}>Explicit assets</option><option value="folder" ${filter.type === 'folder' ? 'selected' : ''}>Source folder</option><option value="tags" ${filter.type === 'tags' ? 'selected' : ''}>Tags</option><option value="collection" ${filter.type === 'collection' ? 'selected' : ''}>Collection</option></select></label>${filterValue}<p>Cover: ${esc(item.coverAssetId || 'None')}</p><button type="button" class="danger" id="delete-record">Delete category</button>`;
  } else {
    form.innerHTML = `${input('Stable ID', 'id', item.id)}${input('Slug', 'slug', item.slug)}${input('Title', 'title', item.title)}<label>Description<textarea name="description">${esc(item.description || '')}</textarea></label>${input('Tags (comma separated)', 'tags', (item.tags || []).join(', '))}<div class="row"><div class="count-card"><span>Total after save</span><strong id="editor-count">${collectionAssets(item).length}</strong><span id="editor-detail">Computed from assigned assets</span></div>${input('Featured order', 'featuredOrder', item.featuredOrder ?? 0, 'number')}</div><label><input name="featured" type="checkbox" ${item.featured ? 'checked' : ''}> Featured</label><label><input name="public" type="checkbox" ${item.public ? 'checked' : ''}> Public</label>${input('Access note', 'accessNote', item.accessNote || '')}<p>Cover: ${esc(item.coverAssetId || 'None')}</p><button type="button" class="danger" id="delete-record">Delete collection</button>`;
  }
  form.querySelector('[name=id]').disabled = true; form.oninput = event => updateFromForm(form, item, event); $('#delete-record').onclick = deleteRecord;
}
function updateFromForm(form, item, event) {
  const data = new FormData(form); const oldSlug = item.slug; item.slug = String(data.get('slug')).trim(); item.title = String(data.get('title')).trim(); item.description = String(data.get('description') || '');
  if (tab === 'categories') { item.order = Number(data.get('order') || 0); item.visible = form.elements.visible.checked; const type = data.get('filterType'); const value = String(data.get('filterValue') || ''); item.filter = type === 'folder' ? { type, category: value || 'Icons' } : type === 'tags' ? { type, tags: value.split(',').map(entry => entry.trim()).filter(Boolean) } : type === 'collection' ? { type, collectionId: value } : { type: 'assets', assetIds: item.filter?.type === 'assets' ? item.filter.assetIds : [] }; }
  else { item.tags = String(data.get('tags') || '').split(',').map(entry => entry.trim()).filter(Boolean); item.featuredOrder = Number(data.get('featuredOrder') || 0); item.featured = form.elements.featured.checked; item.public = form.elements.public.checked; item.accessNote = String(data.get('accessNote') || ''); }
  if (oldSlug !== item.slug && oldSlug) { state.assets.forEach(asset => { asset.collectionSlugs = asset.collectionSlugs.map(slug => slug === oldSlug ? item.slug : slug); }); notice('Published slug changed; asset references will migrate on save.'); }
  renderRecords(); if (event.target.name === 'filterType') renderEditor(); renderAssets();
}
function deleteRecord() { const item = current(); if (!item) return; const affected = tab === 'collections' ? collectionAssets(item).length : categoryAssets(item).length; const featured = tab === 'collections' && item.featured ? ' It is featured.' : ''; if (!confirm(`Delete ${item.title}? ${affected} matched or assigned asset reference(s) are affected.${featured} Source files are never deleted.`)) return; state[tab] = state[tab].filter(entry => entry.id !== item.id); selectedId = state[tab][0]?.id || null; render(); }
function createRecord() { if (tab === 'categories') { const id = nextId(state.categories, 'cat'); state.categories.push({ id, slug: `category-${state.categories.length + 1}`, title: 'New category', description: '', coverAssetId: null, visible: false, order: state.categories.length, filter: { type: 'assets', assetIds: [] } }); selectedId = id; } else { const id = nextId(state.collections, 'col'); state.collections.push({ id, slug: `collection-${state.collections.length + 1}`, title: 'New collection', description: '', coverAssetId: null, tags: [], featured: false, featuredOrder: state.collections.length + 1, public: false, accessNote: '' }); selectedId = id; } render(); }
function updateCounters() {
  const item = current(); if (!item) { $('#selection-count').textContent = '0 selected'; $('#save-summary').textContent = ''; return; }
  const selected = selectedIds(item); const selectedVisible = visibleAssets.filter(asset => selected.has(asset.id)).length; const canPick = tab === 'collections' || item.filter?.type === 'assets';
  $('#selection-count').textContent = canPick ? `${selectedVisible} of ${visibleAssets.length} selected · ${selected.size} total` : `${selected.size} matching assets · ${item.filter?.type || 'no'} filter`;
  $('#asset-count').textContent = `${visibleAssets.length} of ${state.assets.length} assets shown`;
  const before = tab === 'collections' ? original.collections.find(entry => entry.id === item.id) : original.categories.find(entry => entry.id === item.id); const assignedBefore = before ? (tab === 'collections' ? collectionAssets(before, original).length : categoryAssets(before, original).length) : 0;
  $('#save-summary').innerHTML = tab === 'collections' ? `Assigned assets: ${assignedBefore}<br>Selected in current picker: ${selectedVisible}<br>Total after save: ${selected.size}` : `Matching assets: ${selected.size}<br>Current filter: ${esc(item.filter?.type || 'none')}`;
  const editorCount = $('#editor-count'); if (editorCount) editorCount.textContent = selected.size;
  ['select-visible', 'clear-visible', 'clear-all'].forEach(id => { $('#' + id).disabled = !canPick; });
}
function renderAssets() {
  const query = $('#asset-search').value.toLowerCase(); const folder = $('#asset-folder').value; const tag = $('#asset-tag').value.toLowerCase(); const item = current();
  visibleAssets = state.assets.filter(asset => (!query || asset.id.toLowerCase().includes(query) || asset.sourceFile.toLowerCase().includes(query)) && (!folder || asset.category === folder) && (!tag || asset.tags.includes(tag)));
  if ($('#current-only').checked && tab === 'collections' && item) visibleAssets = visibleAssets.filter(asset => asset.collectionSlugs.includes(item.slug));
  const selected = selectedIds(item); const canPick = item && (tab === 'collections' || item.filter?.type === 'assets');
  $('#asset-grid').innerHTML = visibleAssets.slice(0, 500).map(asset => `<article class="asset ${selected.has(asset.id) ? 'selected' : ''}" data-asset-card="${esc(asset.id)}">${canPick ? `<input class="membership" type="checkbox" data-member="${esc(asset.id)}" ${selected.has(asset.id) ? 'checked' : ''} aria-label="Include ${esc(asset.id)}">` : ''}<img src="/source/${encodeURIComponent(asset.sourceFile)}" alt=""><strong>${esc(asset.id)}</strong><small>${esc(asset.sourceFile)}</small><button class="cover-pick" data-cover="${esc(asset.id)}">Use as cover</button></article>`).join('');
  document.querySelectorAll('[data-cover]').forEach(button => button.onclick = () => { if (item) { item.coverAssetId = button.dataset.cover; renderEditor(); updateCounters(); } });
  document.querySelectorAll('[data-member]').forEach(box => box.onchange = () => { setAssetSelected(item, box.dataset.member, box.checked); box.closest('.asset').classList.toggle('selected', box.checked); updateCounters(); }); updateCounters();
}
function setAssetSelected(item, assetId, selected) { if (tab === 'categories') item.filter.assetIds = selected ? [...new Set([...item.filter.assetIds, assetId])] : item.filter.assetIds.filter(id => id !== assetId); else { const asset = state.assets.find(entry => entry.id === assetId); asset.collectionSlugs = selected ? [...new Set([...asset.collectionSlugs, item.slug])] : asset.collectionSlugs.filter(slug => slug !== item.slug); } }
function bulkSelection(mode) { const item = current(); if (!item) return; const ids = mode === 'all' ? state.assets.map(asset => asset.id) : visibleAssets.map(asset => asset.id); for (const id of ids) setAssetSelected(item, id, mode === 'select'); renderAssets(); }
async function save() { const summary = { categories: state.categories.length, collections: state.collections.length, membershipChanges: state.assets.filter(asset => JSON.stringify(asset.collectionSlugs) !== JSON.stringify(original.assets.find(item => item.id === asset.id)?.collectionSlugs || [])).length }; const changedPublishedSlugs = [...state.categories.filter(item => item.visible), ...state.collections.filter(item => item.public)].filter(item => { const before = [...original.categories, ...original.collections].find(entry => entry.id === item.id); return before && before.slug !== item.slug; }); const warning = changedPublishedSlugs.length ? `\nWARNING: ${changedPublishedSlugs.length} published URL slug(s) changed. Existing links may stop working; collection memberships will migrate.\n` : ''; if (!confirm(`Save authored content?${warning}\nCategories: ${summary.categories}\nCollections: ${summary.collections}\nMembership changes: ${summary.membershipChanges}\nCounts will be computed from actual assets.\nA timestamped backup will be created.`)) return; const response = await fetch('/api/save', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(state) }); const result = await response.json(); if (!response.ok) return alert(result.error); notice(`Saved. Backup: ${result.backupPath}`); await load(); }

document.querySelectorAll('[data-tab]').forEach(button => button.onclick = () => { tab = button.dataset.tab; document.querySelectorAll('[data-tab]').forEach(node => node.classList.toggle('active', node === button)); selectedId = state[tab][0]?.id || null; render(); });
$('#create').onclick = createRecord; $('#discard').onclick = () => { if (confirm('Discard all unsaved changes?')) load(); }; $('#save').onclick = save; $('#select-visible').onclick = () => bulkSelection('select'); $('#clear-visible').onclick = () => bulkSelection('visible'); $('#clear-all').onclick = () => bulkSelection('all');
['asset-search', 'asset-folder', 'asset-tag', 'current-only'].forEach(id => $('#' + id).addEventListener('input', renderAssets)); load();
