import { escapeHtml, safeUrl } from '../utils/escape.js';

const option=(item,selected)=>`<option value="${escapeHtml(item.id)}" ${item.id===selected?'selected':''}>${escapeHtml(item.title||item.id)} (${escapeHtml(item.id)})</option>`;
const thumb=asset=>safeUrl(asset?.previewUrl||asset?.previewFile||`/media/previews/${asset?.id||'missing'}.jpg`);
const bindPreviewFallbacks=root=>root.querySelectorAll('img').forEach(image=>image.addEventListener('error',()=>{if(!image.dataset.previewFallback&&/\/media\/previews\/[^/]+\.jpg$/.test(image.src)){image.dataset.previewFallback='true';image.src=image.src.replace(/\.jpg$/,'.webp');}},{once:true}));
const statusLabel=item=>item.requiresDiscordAuth?'Restricted':'Public';

export function mountAdminCatalogEditor(root,{bootstrap,result,client,signal,initialKind='category'}){
  let publicationCleanup=null;let kind=initialKind;let selected=(kind==='category'?result.catalog.categories:result.catalog.collections)[0]?.id||null;let draft=null;let workingMembers=new Set();let assetQuery='';
  const writable=bootstrap.capabilities.writeCatalog===true&&result.readOnly===false;
  const records=()=>kind==='category'?result.catalog.categories:result.catalog.collections;
  const current=()=>draft||records().find(value=>value.id===selected)||null;
  const membersFor=item=>new Set(result.catalog.assets.filter(asset=>asset.collectionSlugs.includes(item.slug)).map(asset=>asset.id));
  const resetMembers=item=>{workingMembers=kind==='collection'&&item?membersFor(item):new Set();};
  resetMembers(current());

  const recordList=()=>records().map(item=>{const cover=result.catalog.assets.find(asset=>asset.id===item.coverAssetId);const count=kind==='collection'?result.catalog.assets.filter(asset=>asset.collectionSlugs.includes(item.slug)).length:0;return `<button type="button" class="admin-record-card${item.id===selected&&!draft?' is-selected':''}" data-record-id="${escapeHtml(item.id)}"><span class="admin-record-cover">${cover?`<img src="${escapeHtml(thumb(cover))}" alt="">`:''}</span><span><strong>${escapeHtml(item.title||item.id)}</strong><small>${escapeHtml(item.id)} · ${kind==='collection'?`${count} images`:(item.visible?'Visible':'Hidden')}</small></span></button>`;}).join('');
  const assetTile=(asset,member)=>`<button type="button" class="admin-picker-card${member?' is-selected':''}" data-member-id="${escapeHtml(asset.id)}" data-picker-search="${escapeHtml(`${asset.id} ${asset.title||''} ${asset.category||''}`.toLowerCase())}" aria-pressed="${member}"><span class="admin-picker-thumb"><img src="${escapeHtml(thumb(asset))}" alt="" loading="lazy"></span><span><strong>${escapeHtml(asset.title||asset.id)}</strong><small>${escapeHtml(asset.id)} · ${escapeHtml(asset.category||'Uncategorized')}</small></span><span class="admin-picker-action">${member?'Remove':'Add'}</span></button>`;
  const form=item=>{
    const coverOptions=result.catalog.assets.map(asset=>option(asset,item.coverAssetId)).join('');
    const memberAssets=result.catalog.assets.filter(asset=>workingMembers.has(asset.id));
    return `<form class="admin-editor-form"><div class="admin-form-grid"><label>Title<input name="title" value="${escapeHtml(item.title||'')}" ${writable?'':'disabled'}></label><label>Slug<input name="slug" value="${escapeHtml(item.slug||'')}" ${writable?'':'disabled'}></label><label class="admin-field-wide">Description<textarea name="description" rows="3" ${writable?'':'disabled'}>${escapeHtml(item.description||'')}</textarea></label><label>Cover image<select name="coverAssetId" ${writable?'':'disabled'}><option value="">None</option>${coverOptions}</select></label><label class="admin-switch"><input name="published" type="checkbox" ${(kind==='category'?item.visible:item.public)?'checked':''} ${writable?'':'disabled'}><span>${kind==='category'?'Visible on site':'Public collection'}</span></label></div>${kind==='collection'?`<section class="admin-members"><div class="admin-subheading"><div><h3>Collection images</h3><p><strong data-member-count>${workingMembers.size}</strong> selected. Click a thumbnail to add or remove it.</p></div></div><div class="admin-member-strip" data-member-strip>${memberAssets.length?memberAssets.map(asset=>assetTile(asset,true)).join(''):'<p class="admin-empty">No images in this collection yet.</p>'}</div><div class="admin-subheading admin-available-heading"><div><h3>Available assets</h3><p>Search the full visual library.</p></div><label class="admin-search">Search assets<input type="search" data-member-search value="${escapeHtml(assetQuery)}" placeholder="Search title or ID"></label></div><div class="admin-picker-grid" data-picker-grid>${result.catalog.assets.map(asset=>assetTile(asset,workingMembers.has(asset.id))).join('')}</div><p class="admin-empty" data-picker-empty hidden>No assets match this search.</p></section>`:''}<div class="admin-form-actions">${writable?`<button class="button button-light" type="submit">Save changes</button><button class="button button-dark" type="button" data-editor-cancel>Cancel</button>${draft?'':`<button class="button button-danger" type="button" data-editor-delete>Delete ${kind}</button>`}`:'<span class="admin-source-badge">Read-only here</span>'}</div></form>`;
  };
  const render=()=>{
    const item=current();const title=kind==='collection'?'Collections':'Categories';
    root.innerHTML=`<div class="admin-section-heading"><div><p class="admin-kicker">Catalog</p><h2>${title}</h2><p>${kind==='collection'?'Select a collection, then add or remove images visually.':'Manage category labels, covers, and visibility.'}</p></div>${writable?`<button type="button" class="button button-dark" data-editor-create>Create ${kind}</button>`:''}</div><div class="admin-editor-layout"><aside class="admin-record-list" aria-label="${title}">${recordList()||'<p>No records.</p>'}</aside><div class="admin-editor-detail">${item?form(item):'<div class="admin-empty">Select a record to begin.</div>'}<p class="admin-publication-status" data-editor-status aria-live="polite"></p></div></div>`;
    bind(item);filterPicker();bindPreviewFallbacks(root);
  };
  const rerenderMembers=()=>{const item=current();if(!item)return;const strip=root.querySelector('[data-member-strip]'),count=root.querySelector('[data-member-count]');const selectedAssets=result.catalog.assets.filter(asset=>workingMembers.has(asset.id));if(strip)strip.innerHTML=selectedAssets.length?selectedAssets.map(asset=>assetTile(asset,true)).join(''):'<p class="admin-empty">No images in this collection yet.</p>';if(count)count.textContent=workingMembers.size;root.querySelectorAll('[data-picker-grid] [data-member-id]').forEach(button=>{const member=workingMembers.has(button.dataset.memberId);button.classList.toggle('is-selected',member);button.setAttribute('aria-pressed',String(member));button.querySelector('.admin-picker-action').textContent=member?'Remove':'Add';});bindMemberButtons();bindPreviewFallbacks(root);};
  const toggleMember=id=>{if(!writable)return;workingMembers.has(id)?workingMembers.delete(id):workingMembers.add(id);rerenderMembers();};
  const bindMemberButtons=()=>root.querySelectorAll('[data-member-id]').forEach(button=>button.onclick=()=>toggleMember(button.dataset.memberId));
  const filterPicker=()=>{const grid=root.querySelector('[data-picker-grid]');if(!grid)return;let visible=0;grid.querySelectorAll('[data-picker-search]').forEach(card=>{const match=!assetQuery||card.dataset.pickerSearch.includes(assetQuery);card.hidden=!match;if(match)visible++;});const empty=root.querySelector('[data-picker-empty]');if(empty)empty.hidden=visible!==0;};
  const bind=item=>{
    root.querySelectorAll('[data-record-id]').forEach(button=>button.onclick=()=>{selected=button.dataset.recordId;draft=null;assetQuery='';resetMembers(current());render();});
    root.querySelector('[data-editor-create]')?.addEventListener('click',()=>{draft=kind==='category'?{title:'New category',slug:`category-${records().length+1}`,description:'',coverAssetId:null,visible:false,order:records().length,filter:{type:'assets',assetIds:[]}}:{title:'New collection',slug:`collection-${records().length+1}`,description:'',coverAssetId:null,tags:[],featured:false,public:false};workingMembers=new Set();render();});
    root.querySelector('[data-editor-cancel]')?.addEventListener('click',()=>{draft=null;assetQuery='';resetMembers(current());render();});
    root.querySelector('[data-editor-delete]')?.addEventListener('click',()=>publish({type:`${kind}.delete`,id:item.id,confirmation:`${kind}.delete`}));
    const search=root.querySelector('[data-member-search]');if(search)search.oninput=event=>{assetQuery=event.target.value.trim().toLowerCase();filterPicker();};
    bindMemberButtons();
    root.querySelector('form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const changes={title:String(data.get('title')),slug:String(data.get('slug')),description:String(data.get('description')),coverAssetId:data.get('coverAssetId')||null,[kind==='category'?'visible':'public']:data.get('published')==='on',...(kind==='collection'?{assetIds:[...workingMembers]}:{})};const type=`${kind}.${draft?'create':'update'}`;publish({type,...(!draft?{id:item.id}:{}),changes,...(!draft&&changes.slug!==item.slug?{confirmation:type}:{})});});
  };
  const publish=async mutation=>{if((mutation.type.endsWith('.delete')||mutation.confirmation)&&!confirm('Publish this potentially destructive catalog change?'))return;const status=root.querySelector('[data-editor-status]');status.textContent='Validating and publishing…';try{const response=await client.publish({baseCommitSha:result.baseCommitSha,mutation},bootstrap.csrfToken,crypto.randomUUID(),signal);const body=await response.json();if(response.status===409){status.textContent='Another catalog change was published first. Your selections are still here; reload the catalog before retrying.';return;}if(!response.ok){status.textContent=body.error||'Publication failed.';return;}status.textContent=`Committed as ${body.publication.commitSha}. Deployment is pending.`;if(bootstrap.capabilities.verifyDeployments){const {monitorAdminPublication}=await import('./AdminPublicationStatus.js');publicationCleanup=monitorAdminPublication(status,{publicationId:body.publication.publicationId,bootstrap,client,signal,onLive:()=>location.reload()});}}catch(error){if(error.name!=='AbortError')status.textContent='Publication could not be reached. Your selections are still here.';}};
  render();
  return()=>publicationCleanup?.();
}
