import { escapeHtml } from '../utils/escape.js';

const option=(item,selected)=>`<option value="${escapeHtml(item.id)}" ${item.id===selected?'selected':''}>${escapeHtml(item.title||item.id)} (${escapeHtml(item.id)})</option>`;
export function mountAdminCatalogEditor(root,{bootstrap,result,client,signal}){
  let uploadCleanup=null;let publicationCleanup=null;
  let kind='category'; let selected=result.catalog.categories[0]?.id||null; let draft=null; const records=()=>kind==='category'?result.catalog.categories:result.catalog.collections;
  const form=item=>`<form class="admin-editor-form"><label>Title<input name="title" value="${escapeHtml(item.title||'')}"></label><label>Slug<input name="slug" value="${escapeHtml(item.slug||'')}"></label><label>Description<textarea name="description">${escapeHtml(item.description||'')}</textarea></label><label>Cover asset<select name="coverAssetId"><option value="">None</option>${result.catalog.assets.map(asset=>option(asset,item.coverAssetId)).join('')}</select></label><label><input name="published" type="checkbox" ${(kind==='category'?item.visible:item.public)?'checked':''}> ${kind==='category'?'Visible':'Public'}</label>${kind==='collection'?`<fieldset><legend>Membership</legend>${result.catalog.assets.map(asset=>`<label><input type="checkbox" name="assetIds" value="${escapeHtml(asset.id)}" ${asset.collectionSlugs.includes(item.slug)?'checked':''}> ${escapeHtml(asset.title||asset.id)}</label>`).join('')}</fieldset>`:''}<div><button class="button button-light button-compact" type="submit">Publish change</button>${draft?'<button class="button button-dark button-compact" type="button" data-editor-cancel>Cancel</button>':`<button class="button button-dark button-compact" type="button" data-editor-delete>Delete</button>`}</div></form>`;
  const render=()=>{const item=draft||records().find(value=>value.id===selected);root.innerHTML=`${bootstrap.capabilities.uploadAssets?'<div class="admin-upload-mount"><button class="button button-light button-compact" type="button" data-open-upload>Upload asset</button></div>':''}<div class="admin-editor-heading"><div><h2>Catalog editor</h2><p>One validated change is committed at a time.</p></div><span class="admin-readonly-badge">Git-backed</span></div><div class="admin-editor-toolbar"><label>Record type<select data-editor-kind><option value="category" ${kind==='category'?'selected':''}>Categories</option><option value="collection" ${kind==='collection'?'selected':''}>Collections</option></select></label><label>Record<select data-editor-record>${records().map(value=>option(value,selected)).join('')}</select></label><button type="button" class="button button-dark button-compact" data-editor-create>Create</button></div>${item?form(item):'<p>No records.</p>'}<p data-editor-status aria-live="polite"></p>`;bind(item);};
  const bind=item=>{root.querySelector('[data-open-upload]')?.addEventListener('click',async()=>{const mount=root.querySelector('.admin-upload-mount');mount.innerHTML='<p>Loading upload tools…</p>';const {mountAdminAssetUpload}=await import('./AdminAssetUpload.js');if(!signal.aborted)uploadCleanup=mountAdminAssetUpload(mount,{bootstrap,result,client,parentSignal:signal});});root.querySelector('[data-editor-kind]').onchange=e=>{kind=e.target.value;selected=records()[0]?.id||null;draft=null;render();};root.querySelector('[data-editor-record]').onchange=e=>{selected=e.target.value;draft=null;render();};root.querySelector('[data-editor-create]').onclick=()=>{draft=kind==='category'?{title:'New category',slug:`category-${records().length+1}`,description:'',coverAssetId:null,visible:false,order:records().length,filter:{type:'assets',assetIds:[]}}:{title:'New collection',slug:`collection-${records().length+1}`,description:'',coverAssetId:null,tags:[],featured:false,public:false,assetIds:[]};render();};root.querySelector('[data-editor-cancel]')?.addEventListener('click',()=>{draft=null;render();});root.querySelector('[data-editor-delete]')?.addEventListener('click',()=>publish({type:`${kind}.delete`,id:item.id,confirmation:`${kind}.delete`}));root.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const changes={title:String(data.get('title')),slug:String(data.get('slug')),description:String(data.get('description')),coverAssetId:data.get('coverAssetId')||null,[kind==='category'?'visible':'public']:data.get('published')==='on',...(kind==='collection'?{assetIds:data.getAll('assetIds')}:{})};const type=`${kind}.${draft?'create':'update'}`;publish({type,...(!draft?{id:item.id}:{}),changes,...(!draft&&changes.slug!==item.slug?{confirmation:type}:{})});});};
  const publish=async mutation=>{if((mutation.type.endsWith('.delete')||mutation.confirmation)&&!confirm('Publish this potentially destructive catalog change?'))return;const status=root.querySelector('[data-editor-status]');status.textContent='Validating and publishingâ€¦';try{const response=await client.publish({baseCommitSha:result.baseCommitSha,mutation},bootstrap.csrfToken,crypto.randomUUID(),signal);const body=await response.json();if(response.status===409){status.textContent='Another catalog change was published first. Your form remains available; reload the catalog before retrying.';return;}if(!response.ok){status.textContent=body.error||'Publication failed.';return;}status.textContent=`Committed as ${body.publication.commitSha}. Deployment is pending.`;if(bootstrap.capabilities.verifyDeployments){const {monitorAdminPublication}=await import('./AdminPublicationStatus.js');publicationCleanup=monitorAdminPublication(status,{publicationId:body.publication.publicationId,bootstrap,client,signal,onLive:()=>location.reload()});}}catch(error){if(error.name!=='AbortError')status.textContent='Publication could not be reached. Your form remains available.';}};
  render();
  return()=>{uploadCleanup?.();publicationCleanup?.();};
}
