import {beforeAll,describe,expect,it} from 'vitest';
import {SESSION_COOKIE} from '../../server/auth.js';
import {signPayload} from '../../server/crypto.js';
import {createLocalAdminCatalogProvider} from '../../scripts/admin/local-catalog-provider.mjs';
import {createMockGitProvider} from '../../server/admin/mock-git-provider.js';
import {createMockCloudinaryProvider} from '../../server/admin/cloudinary-provider.js';
import {createMemoryUploadStore} from '../../server/admin/upload-store.js';
import {onRequest as createEndpoint} from '../../functions/api/admin/uploads.js';
import {onRequest as getEndpoint} from '../../functions/api/admin/uploads/[jobId].js';
import {onRequest as finalizeEndpoint} from '../../functions/api/admin/uploads/[jobId]/finalize.js';

const secret='a sufficiently long upload endpoint test secret',owner='1137950746751537152',delegated='2237950746751537152',ordinary='3237950746751537152',sha='a'.repeat(40);let snapshot;
beforeAll(async()=>{snapshot=(await createLocalAdminCatalogProvider({baseCommitSha:sha}).read()).snapshot;});
const db={prepare(){return{bind(id){return{first:async()=>id===delegated?{discord_id:id}:null};}};}};
const env=(extra={})=>({SESSION_SECRET:secret,ADMIN_OWNER_DISCORD_ID:owner,ADMIN_DB:db,ADMIN_ENVIRONMENT:'test',ADMIN_ALLOW_LOCAL_WRITES:'true',...extra});
const data=(restricted=false)=>({adminGitProvider:createMockGitProvider({head:sha,snapshot}),adminCloudinaryProvider:createMockCloudinaryProvider({restrictedEnabled:restricted}),uploadStore:createMemoryUploadStore(),enableRestrictedUploads:restricted});
async function req(id,path='/api/admin/uploads',{method='POST',origin='https://www.pfseeker.com',csrf='csrf',key='upload-request-1',body={baseCommitSha:sha,category:'Icons',logicalSourceFilename:'x.png',title:'X',tags:[],collectionSlugs:[],requiresDiscordAuth:false,declaredFile:{format:'png',bytes:100}}}={}){const token=id?await signPayload({user:{id,displayName:'Admin'},csrf:'csrf',exp:9_999_999_999},secret):null;return new Request(`https://www.pfseeker.com${path}`,{method,headers:{...(token?{Cookie:`${SESSION_COOKIE}=${encodeURIComponent(token)}`}:{ }),Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':key},...(method==='GET'?{}:{body:JSON.stringify(body)})});}
describe('Phase 6 upload endpoints',()=>{
  it('authorizes owner and delegated and rejects signed-out, ordinary, preview, origin, and CSRF',async()=>{for(const [id,status] of [[null,401],[ordinary,403],[owner,201],[delegated,201]])expect((await createEndpoint({request:await req(id),env:env(),data:data()})).status).toBe(status);expect((await createEndpoint({request:await req(owner),env:env({ADMIN_ENVIRONMENT:'preview'}),data:data()})).status).toBe(403);expect((await createEndpoint({request:await req(owner,'/api/admin/uploads',{origin:'https://evil.example'}),env:env(),data:data()})).status).toBe(403);expect((await createEndpoint({request:await req(owner,'/api/admin/uploads',{csrf:'bad'}),env:env(),data:data()})).status).toBe(403);});
  it('uses no-store and independently authorizes job inspection and finalization',async()=>{const shared=data();const created=await createEndpoint({request:await req(owner),env:env(),data:shared});const value=await created.json(),jobId=value.job.jobId;expect(created.headers.get('Cache-Control')).toBe('no-store');const got=await getEndpoint({request:await req(owner,`/api/admin/uploads/${jobId}`,{method:'GET'}),env:env(),data:shared,params:{jobId}});expect(got.status).toBe(200);expect(got.headers.get('Cache-Control')).toBe('no-store');const denied=await getEndpoint({request:await req(ordinary,`/api/admin/uploads/${jobId}`,{method:'GET'}),env:env(),data:shared,params:{jobId}});expect(denied.status).toBe(403);const finalized=await finalizeEndpoint({request:await req(owner,`/api/admin/uploads/${jobId}/finalize`,{key:'finalize-key-1',body:{version:1700000000}}),env:env(),data:shared,params:{jobId}});expect(finalized.status).toBe(202);expect(finalized.headers.get('Cache-Control')).toBe('no-store');});
  it('never returns provider secrets or accepts client identity controls',async()=>{const response=await createEndpoint({request:await req(owner,'/api/admin/uploads',{body:{baseCommitSha:sha,category:'Icons',logicalSourceFilename:'x.png',title:'X',tags:[],collectionSlugs:[],requiresDiscordAuth:false,declaredFile:{format:'png',bytes:1},assetId:'nv-999',publicId:'evil',folder:'evil',type:'authenticated',transformation:'evil'}}),env:env(),data:data()});const text=await response.text();expect(response.status).toBe(201);expect(text).not.toMatch(/api.?secret|ADMIN_DB|GITHUB|nv-999|"evil"/i);expect(text).toContain('neuevault/public/icons/');});
  it('enables restricted authorization only through an explicit complete local capability',async()=>{const body={baseCommitSha:sha,category:'Icons',logicalSourceFilename:'x.gif',title:'X',tags:[],collectionSlugs:[],requiresDiscordAuth:true,declaredFile:{format:'gif',bytes:100}};expect((await createEndpoint({request:await req(owner,'/api/admin/uploads',{body,key:'restricted-off'}),env:env(),data:data()})).status).toBe(400);const response=await createEndpoint({request:await req(owner,'/api/admin/uploads',{body,key:'restricted-on'}),env:env(),data:data(true)}),text=await response.text();expect(response.status).toBe(201);expect(text).toContain('neuevault/restricted/icons/');expect(text).toContain('authenticated');expect(text).not.toMatch(/private_download_url|transformation|api.?secret/i);});
});
