import {beforeAll,describe,expect,it} from 'vitest';
import {createLocalAdminCatalogProvider} from '../../scripts/admin/local-catalog-provider.mjs';
import {createMockGitProvider} from '../../server/admin/mock-git-provider.js';
import {createMockCloudinaryProvider,publicIdFor,restrictedOriginalPublicIdFor,restrictedPreviewPublicIdFor,UPLOAD_LIMITS} from '../../server/admin/cloudinary-provider.js';
import {createMemoryUploadStore} from '../../server/admin/upload-store.js';
import {assertUploadTransition} from '../../server/admin/upload-state.js';
import {createUploadJob,finalizeUploadJob,retryUploadPublication} from '../../server/admin/uploads.js';

const sha='a'.repeat(40),admin={discordId:'1137950746751537152',role:'owner'};let snapshot;
beforeAll(async()=>{snapshot=(await createLocalAdminCatalogProvider({baseCommitSha:sha}).read()).snapshot;});
const body=(extra={})=>({baseCommitSha:sha,category:'Icons',logicalSourceFilename:'new.png',title:'New image',tags:['New'],collectionSlugs:[],requiresDiscordAuth:false,declaredFile:{format:'png',bytes:1024},...extra});
const fixture=(cloudinary=createMockCloudinaryProvider())=>{const git=createMockGitProvider({head:sha,snapshot}),store=createMemoryUploadStore();return {git,store,cloudinary,context:{env:{},data:{adminGitProvider:git,adminCloudinaryProvider:cloudinary,uploadStore:store}}};};
describe('Phase 6 upload staging',()=>{
  it('reserves a server ID, constrains signing for ten minutes, and replays creation',async()=>{const f=fixture(),input={admin,requestId:'r',idempotencyKey:'upload-key-1',body:body(),now:new Date('2026-08-06T00:00:00Z')};const first=await createUploadJob(f.context,input),again=await createUploadJob(f.context,input);expect(first.job.assetId).toMatch(/^nv-\d+$/);expect(first.authorization.expectedPublicId).toBe(publicIdFor('Icons',first.job.assetId));expect(first.authorization.expiresAt).toBe('2026-08-06T00:10:00.000Z');expect(first.authorization).not.toHaveProperty('apiSecret');expect(first.authorization.parameters).toMatchObject({resource_type:'image',type:'upload',overwrite:'false'});expect(again.replayed).toBe(true);expect(f.store.values).toHaveLength(1);await expect(createUploadJob(f.context,{...input,body:body({title:'Different'})})).rejects.toMatchObject({code:'idempotency_key_reused'});});
  it('rejects restricted, invalid category/collection, unsupported, and oversized declarations',async()=>{for(const [extra,code] of [[{requiresDiscordAuth:true},'restricted_upload_disabled'],[{category:'Nope'},'upload_category_invalid'],[{collectionSlugs:['missing']},'upload_collection_invalid'],[{declaredFile:{format:'svg',bytes:2}},'upload_format_unsupported'],[{declaredFile:{format:'png',bytes:UPLOAD_LIMITS.bytes+1}},'upload_file_too_large']])await expect(createUploadJob(fixture().context,{admin,requestId:'r',idempotencyKey:`key-${code}`,body:body(extra)})).rejects.toMatchObject({code});});
  it('independently verifies, compiles, updates Cloudinary state, and commits eight files',async()=>{const f=fixture();const made=await createUploadJob(f.context,{admin,requestId:'r',idempotencyKey:'upload-key-2',body:body(),now:new Date('2026-08-06T00:00:00Z')});const done=await finalizeUploadJob(f.context,{admin,requestId:'f',jobId:made.job.jobId,idempotencyKey:'final-key-2',body:{version:1700000000},now:new Date('2026-08-06T00:01:00Z')});expect(done.status).toBe('deployment_pending');expect(f.cloudinary.verifications).toHaveLength(1);expect(f.git.commits).toHaveLength(1);expect(f.git.commits[0].files).toHaveLength(8);expect(f.git.commits[0].files.map(v=>v.path)).toContain('content/cloudinary-sync.json');const generated=JSON.parse(f.git.commits[0].files.find(v=>v.path==='src/generated/assets.json').content);expect(generated.find(v=>v.id===made.job.assetId)).toMatchObject({requiresDiscordAuth:false,width:1200,height:800,src:expect.stringMatching(/^https:/)});expect(generated.find(v=>v.id==='nv-166').src).toBeNull();});
  it.each([['jpg',false],['png',false],['gif',true],['webp',true]])('accepts verified %s facts and derives animation only from the provider',(async(format,animated)=>{const cloudinary=createMockCloudinaryProvider();cloudinary.verifyResource=async input=>({assetId:`asset-${format}`,publicId:input.publicId,version:2,resourceType:'image',deliveryType:'upload',format,bytes:100,width:20,height:10,pages:animated?2:1,animated,secureUrl:`https://example.test/${input.publicId}.${format}`,createdAt:'2026-08-06T00:00:00Z'});const f=fixture(cloudinary),made=await createUploadJob(f.context,{admin,requestId:'r',idempotencyKey:`create-${format}`,body:body({declaredFile:{format,bytes:50}}),now:new Date('2026-08-06T00:00:00Z')});await finalizeUploadJob(f.context,{admin,requestId:'f',jobId:made.job.jobId,idempotencyKey:`final-${format}`,body:{version:2},now:new Date('2026-08-06T00:01:00Z')});const generated=JSON.parse(f.git.commits[0].files.find(value=>value.path==='src/generated/assets.json').content).find(value=>value.id===made.job.assetId);expect(generated).toMatchObject({animated,fileType:format==='jpg'?'JPG':format.toUpperCase()});}));
  it('fails closed on verified identity and media limits',async()=>{for(const [resource,code] of [[{publicId:'wrong'},'upload_public_id_mismatch'],[{bytes:UPLOAD_LIMITS.bytes+1},'upload_file_too_large'],[{width:12001},'upload_width_exceeded'],[{height:12001},'upload_height_exceeded'],[{width:11000,height:10000},'upload_pixels_exceeded'],[{format:'svg'},'upload_format_unsupported'],[{deliveryType:'authenticated'},'upload_delivery_invalid']]){const f=fixture(createMockCloudinaryProvider({resource:{assetId:'x',publicId:'placeholder',version:1,resourceType:'image',deliveryType:'upload',format:'png',bytes:2,width:2,height:2,pages:1,secureUrl:'https://example.test/x.png',createdAt:'2026-08-06T00:00:00Z',...resource}}));const made=await createUploadJob(f.context,{admin,requestId:'r',idempotencyKey:`upload-${code}`,body:body(),now:new Date('2026-08-06T00:00:00Z')});if(resource.publicId!=='wrong')f.cloudinary.verifyResource=async input=>({...await createMockCloudinaryProvider().verifyResource(input),...resource});await expect(finalizeUploadJob(f.context,{admin,requestId:'f',jobId:made.job.jobId,idempotencyKey:`final-${code}`,body:{version:1},now:new Date('2026-08-06T00:01:00Z')})).rejects.toMatchObject({code});expect(f.git.commits).toHaveLength(0);}});
  it('enforces legal upload transitions',()=>{expect(()=>assertUploadTransition('created','verifying')).toThrow();expect(()=>assertUploadTransition('verified','publication_pending')).not.toThrow();expect(()=>assertUploadTransition('cleanup_eligible','cleaned')).not.toThrow();});
  it('retries a stale-base publication without re-upload or duplicate verification',async()=>{const f=fixture();const made=await createUploadJob(f.context,{admin,requestId:'r',idempotencyKey:'upload-conflict',body:body(),now:new Date('2026-08-06T00:00:00Z')});const external=await f.git.createCommit({baseSha:sha,files:[{path:'public/catalog-version.json',content:'{"version":1}'}],message:'external'});await expect(finalizeUploadJob(f.context,{admin,requestId:'f',jobId:made.job.jobId,idempotencyKey:'final-conflict',body:{version:1},now:new Date('2026-08-06T00:01:00Z')})).rejects.toMatchObject({code:'catalog_conflict'});const retried=await retryUploadPublication(f.context,{admin,requestId:'retry',jobId:made.job.jobId,baseCommitSha:external.commitSha,idempotencyKey:'retry-key-1',now:new Date('2026-08-06T00:02:00Z')});expect(retried.status).toBe('deployment_pending');expect(f.cloudinary.verifications).toHaveLength(1);expect(f.git.commits).toHaveLength(2);expect((await retryUploadPublication(f.context,{admin,requestId:'retry',jobId:made.job.jobId,baseCommitSha:external.commitSha,idempotencyKey:'retry-key-1'})).replayed).toBe(true);});
  it.each([['jpg',false,'jpg'],['png',false,'png'],['gif',true,'png'],['webp',true,'png']])('publishes a safe restricted %s with an independently verified static preview',async(format,animated,previewFormat)=>{const cloudinary=createMockCloudinaryProvider({restrictedEnabled:true}),f=fixture(cloudinary);cloudinary.verifyResource=async input=>{cloudinary.verifications.push(structuredClone(input));if(input.deliveryType==='authenticated')return {assetId:`original-${format}`,publicId:input.publicId,version:2,resourceType:'image',deliveryType:'authenticated',format,bytes:100,width:800,height:400,pages:animated?3:1,animated,createdAt:'2026-08-06T00:00:00Z'};return {assetId:`preview-${format}`,publicId:input.publicId,version:3,resourceType:'image',deliveryType:'upload',format:previewFormat,bytes:50,width:800,height:400,pages:1,animated:false,secureUrl:`https://res.cloudinary.com/local-mock/image/upload/v3/${input.publicId}.${previewFormat}`,createdAt:'2026-08-06T00:00:01Z'};};const made=await createUploadJob(f.context,{admin,requestId:'r',idempotencyKey:`restricted-${format}`,body:body({requiresDiscordAuth:true,declaredFile:{format,bytes:80}}),allowRestricted:true,now:new Date('2026-08-06T00:00:00Z')});expect(made.authorization.expectedPublicId).toBe(restrictedOriginalPublicIdFor('Icons',made.job.assetId));expect(made.authorization.parameters.type).toBe('authenticated');await finalizeUploadJob(f.context,{admin,requestId:'f',jobId:made.job.jobId,idempotencyKey:`restricted-final-${format}`,body:{version:2},now:new Date('2026-08-06T00:01:00Z')});expect(cloudinary.previewCreations[0].previewPublicId).toBe(restrictedPreviewPublicIdFor('Icons',made.job.assetId));expect(cloudinary.verifications.map(value=>value.deliveryType)).toEqual(['authenticated','upload']);const commit=f.git.commits[0],generated=JSON.parse(commit.files.find(value=>value.path==='src/generated/assets.json').content).find(value=>value.id===made.job.assetId),sync=JSON.parse(commit.files.find(value=>value.path==='content/cloudinary-sync.json').content).assets[made.job.assetId];expect(generated).toMatchObject({requiresDiscordAuth:true,src:null,animated,cloudinaryDeliveryType:'authenticated'});expect(generated.previewUrl).toContain('/previews/');expect(sync.original).not.toHaveProperty('secureUrl');expect(sync.preview.secureUrl).toContain('/previews/');expect(JSON.stringify({job:f.store.values[0],commit})).not.toMatch(/private_download_url|expires_at=.*signature|api_secret/i);});
  it('fails restricted publication for an animated, colliding, or wrong-delivery preview',async()=>{for(const [override,code] of [[{animated:true,pages:2},'restricted_preview_animated'],[{assetId:'original'},'restricted_preview_identity_collision'],[{deliveryType:'authenticated'},'restricted_preview_delivery_invalid']]){const cloudinary=createMockCloudinaryProvider({restrictedEnabled:true}),f=fixture(cloudinary);cloudinary.verifyResource=async input=>input.deliveryType==='authenticated'?{assetId:'original',publicId:input.publicId,version:2,resourceType:'image',deliveryType:'authenticated',format:'gif',bytes:100,width:20,height:10,pages:2,animated:true,createdAt:'2026-08-06'}:{assetId:'preview',publicId:input.publicId,version:3,resourceType:'image',deliveryType:'upload',format:'png',bytes:50,width:20,height:10,pages:1,animated:false,secureUrl:`https://res.cloudinary.com/x/image/upload/v3/${input.publicId}.png`,...override};const made=await createUploadJob(f.context,{admin,requestId:'r',idempotencyKey:`restricted-fail-${code}`,body:body({requiresDiscordAuth:true,declaredFile:{format:'gif',bytes:80}}),allowRestricted:true});await expect(finalizeUploadJob(f.context,{admin,requestId:'f',jobId:made.job.jobId,idempotencyKey:`restricted-final-${code}`,body:{version:2}})).rejects.toMatchObject({code});expect(f.git.commits).toHaveLength(0);expect(f.store.values[0]).toMatchObject({status:'failed',recoverable:true,cleanupState:'not_eligible'});}});
});
