import { describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { AdminError } from '../../server/admin/errors.js';
import { createGitHubAppJwt, createGitHubAppProvider, GITHUB_TARGET } from '../../server/admin/github-app-provider.js';
import { createCloudinaryProductionProvider, RESTRICTED_PREVIEW_POLICY, signCloudinaryParameters } from '../../server/admin/cloudinary-provider.js';
import { adminProviderCompleteness } from '../../server/admin/capabilities.js';
import { createCloudflareDeploymentVerifier, createMockDeploymentVerifier, DEPLOYMENT_TARGET } from '../../server/admin/deployment-verifier.js';
import { verifyPublicationDeployment } from '../../server/admin/deployment-verification.js';
import { createMemoryPublicationStore } from '../../server/admin/publication-store.js';
import { createMemoryUploadStore } from '../../server/admin/upload-store.js';

const base64=value=>btoa(String.fromCharCode(...new Uint8Array(value)));
async function privateKey(){const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const bytes=await crypto.subtle.exportKey('pkcs8',pair.privateKey);return `-----BEGIN PRIVATE KEY-----\n${base64(bytes).match(/.{1,64}/g).join('\n')}\n-----END PRIVATE KEY-----`;}
const owner='1137950746751537152',commit='a'.repeat(40),catalogDigest='b'.repeat(64),now=new Date('2026-08-06T00:00:00Z');

describe('production readiness command',()=>{
  it('is explicitly read-only and never calls provider mutation methods',()=>{const source=readFileSync('scripts/admin/production-readiness.mjs','utf8');expect(source).toContain("process.argv[2] !== '--read-only'");expect(source).toContain("ADMIN_PRODUCTION_WRITES_ENABLED === 'false'");expect(source).toMatch(/\.readHead\(\)|\.readSnapshot\(head\)|\.verifyResource\(/);expect(source).not.toMatch(/\.createCommit\(|\.createUploadAuthorization\(|\.createRestrictedPreview\(|method:\s*['\"](?:POST|PUT|PATCH|DELETE)/);});
});

describe('GitHub App production adapter',()=>{
  it('creates a short-lived RS256 JWT with the configured app issuer',async()=>{const jwt=await createGitHubAppJwt({appId:'123',privateKey:await privateKey()},now),parts=jwt.split('.');const payload=JSON.parse(atob(parts[1].replace(/-/g,'+').replace(/_/g,'/')));expect(parts).toHaveLength(3);expect(payload).toMatchObject({iss:'123'});expect(payload.exp-payload.iat).toBe(540);expect(jwt).not.toContain('PRIVATE KEY');});
  it('fixes repository identity and fails closed for malformed configuration',()=>{expect(GITHUB_TARGET).toEqual({owner:'666forever',repository:'neuevault',branch:'main'});expect(createGitHubAppProvider({env:{GITHUB_APP_ID:'x',GITHUB_APP_PRIVATE_KEY:'secret',GITHUB_APP_INSTALLATION_ID:'2'}})).toBeNull();});
  it('requests least-privilege installation access, reuses the token, and reads the fixed head',async()=>{const key=await privateKey(),requests=[];vi.stubGlobal('fetch',vi.fn(async(url,options={})=>{requests.push({url:String(url),options});if(String(url).includes('/access_tokens'))return new Response(JSON.stringify({token:'installation-token',expires_at:'2026-08-06T01:00:00Z',permissions:{contents:'write',metadata:'read'},repositories:[{name:'neuevault',owner:{login:'666forever'}}]}),{status:201,headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify({ref:'refs/heads/main',object:{type:'commit',sha:commit}}),{status:200,headers:{'Content-Type':'application/json'}});}));const provider=createGitHubAppProvider({env:{GITHUB_APP_ID:'123',GITHUB_APP_PRIVATE_KEY:key,GITHUB_APP_INSTALLATION_ID:'456'},now:()=>now});expect(await provider.readHead()).toBe(commit);expect(await provider.readHead()).toBe(commit);expect(requests.filter(value=>value.url.includes('/access_tokens'))).toHaveLength(1);const tokenBody=JSON.parse(requests[0].options.body);expect(tokenBody).toEqual({repositories:['neuevault'],permissions:{contents:'write',metadata:'read'}});expect(requests.every(value=>!JSON.stringify(value).includes('BEGIN PRIVATE KEY'))).toBe(true);vi.unstubAllGlobals();});
  it('creates a one-parent commit and conditionally advances main without force',async()=>{const key=await privateKey(),bodies=[];let head=commit;vi.stubGlobal('fetch',vi.fn(async(url,options={})=>{const path=new URL(url).pathname,b=options.body&&JSON.parse(options.body);if(b)bodies.push({path,body:b});if(path.includes('/access_tokens'))return Response.json({token:'installation-token',expires_at:'2026-08-06T01:00:00Z',permissions:{contents:'write',metadata:'read'},repositories:[{name:'neuevault',owner:{login:'666forever'}}]},{status:201});if(path.endsWith('/git/ref/heads/main'))return Response.json({ref:'refs/heads/main',object:{type:'commit',sha:head}});if(path.endsWith(`/git/commits/${commit}`))return Response.json({sha:commit,tree:{sha:'c'.repeat(40)}});if(path.endsWith('/git/blobs'))return Response.json({sha:'d'.repeat(40)},{status:201});if(path.endsWith('/git/trees'))return Response.json({sha:'e'.repeat(40)},{status:201});if(path.endsWith('/git/commits'))return Response.json({sha:'f'.repeat(40),tree:{sha:'e'.repeat(40)},parents:[{sha:commit}]},{status:201});if(path.endsWith('/git/refs/heads/main')){head='f'.repeat(40);return Response.json({ref:'refs/heads/main',object:{type:'commit',sha:head}});}throw new Error(`Unexpected ${path}`);}));const provider=createGitHubAppProvider({env:{GITHUB_APP_ID:'123',GITHUB_APP_PRIVATE_KEY:key,GITHUB_APP_INSTALLATION_ID:'456'},now:()=>now});await expect(provider.createCommit({baseSha:commit,files:[{path:'public/catalog-version.json',content:'{"version":1}\n'}],message:'catalog: asset.create nv-999'})).resolves.toEqual({commitSha:'f'.repeat(40)});expect(bodies.find(value=>value.path.endsWith('/git/commits')).body.parents).toEqual([commit]);expect(bodies.find(value=>value.path.endsWith('/git/refs/heads/main')).body).toEqual({sha:'f'.repeat(40),force:false});vi.unstubAllGlobals();});
});

describe('Cloudinary production adapter',()=>{
  it('generates deterministic signatures without returning the secret',async()=>{const parameters={public_id:'neuevault/public/icons/nv-999',timestamp:1700000000,overwrite:'false',type:'upload'};const first=await signCloudinaryParameters(parameters,'server-secret'),second=await signCloudinaryParameters(parameters,'server-secret');expect(first).toBe(second);expect(first).toMatch(/^[a-f0-9]{40}$/);expect(first).not.toContain('server-secret');});
  it('returns a constrained signed authorization',async()=>{const provider=createCloudinaryProductionProvider({env:{CLOUDINARY_CLOUD_NAME:'test-cloud',CLOUDINARY_API_KEY:'12345',CLOUDINARY_API_SECRET:'server-secret'}});const value=await provider.createUploadAuthorization({publicId:'neuevault/public/icons/nv-999',timestamp:1700000000,expiresAt:'2023-11-14T22:23:20.000Z'});expect(value.parameters).toMatchObject({public_id:'neuevault/public/icons/nv-999',resource_type:'image',type:'upload',overwrite:'false'});expect(JSON.stringify(value)).not.toContain('server-secret');});
  it('re-reads and normalizes the exact Admin API resource',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json({asset_id:'asset-1',public_id:'neuevault/public/icons/nv-999',version:1700000000,resource_type:'image',type:'upload',format:'png',bytes:1200,width:100,height:50,pages:1,secure_url:'https://res.cloudinary.com/test-cloud/image/upload/v1700000000/neuevault/public/icons/nv-999.png',created_at:'2026-08-06T00:00:00Z'})));const provider=createCloudinaryProductionProvider({env:{CLOUDINARY_CLOUD_NAME:'test-cloud',CLOUDINARY_API_KEY:'12345',CLOUDINARY_API_SECRET:'server-secret'}});await expect(provider.verifyResource({publicId:'neuevault/public/icons/nv-999',version:1700000000})).resolves.toMatchObject({assetId:'asset-1',deliveryType:'upload',format:'png',width:100,height:50});vi.unstubAllGlobals();});
  it('authorizes authenticated originals and materializes a bounded preview without exposing its temporary source',async()=>{let body='';vi.stubGlobal('fetch',vi.fn(async(url,options={})=>{body=String(options.body||'');return Response.json({asset_id:'preview-asset',public_id:'neuevault/previews/icons/nv-999',version:1700000001,resource_type:'image',type:'upload',format:'png',bytes:500,width:100,height:50,pages:1,created_at:'2026-08-06T00:00:01Z'});}));const provider=createCloudinaryProductionProvider({env:{CLOUDINARY_CLOUD_NAME:'test-cloud',CLOUDINARY_API_KEY:'12345',CLOUDINARY_API_SECRET:'server-secret'},now:()=>new Date('2026-08-06T00:00:00Z')});const authorization=await provider.createUploadAuthorization({publicId:'neuevault/restricted/icons/nv-999',requiresDiscordAuth:true,timestamp:1785974400,expiresAt:'2026-08-06T00:10:00.000Z'});expect(authorization.parameters.type).toBe('authenticated');const result=await provider.createRestrictedPreview({original:{assetId:'original-asset',publicId:'neuevault/restricted/icons/nv-999',version:1,resourceType:'image',deliveryType:'authenticated',format:'gif',width:100,height:50},previewPublicId:'neuevault/previews/icons/nv-999'});expect(result).toMatchObject({publicId:'neuevault/previews/icons/nv-999',deliveryType:'upload',format:'png'});const params=new URLSearchParams(body);expect(params.get('transformation')).toBe('pg_1,w_1200,h_1200,c_limit');expect(params.get('type')).toBe('upload');const source=new URL(params.get('file'));expect(Number(source.searchParams.get('expires_at'))-Number(source.searchParams.get('timestamp'))).toBe(RESTRICTED_PREVIEW_POLICY.sourceSeconds);expect(JSON.stringify(result)).not.toContain(source.href);expect(body).not.toContain('server-secret');vi.unstubAllGlobals();});
});

describe('provider completeness and authoritative live transition',()=>{
  it('requires the complete provider set and keeps preview and restricted upload fail closed',()=>{
    const data={publicationStore:{},uploadStore:{},adminGitProvider:{},adminCloudinaryProvider:{},deploymentVerifier:{}};
    const complete=adminProviderCompleteness({env:{ADMIN_ENVIRONMENT:'production',ADMIN_OWNER_DISCORD_ID:owner},data});
    expect(complete).toMatchObject({catalogWrites:true,uploads:true,restrictedUploads:false,deploymentVerification:true});
    expect(adminProviderCompleteness({env:{ADMIN_ENVIRONMENT:'production',ADMIN_OWNER_DISCORD_ID:owner},data:{publicationStore:{},adminGitProvider:{}}}).uploads).toBe(false);
    const restrictedProvider={supportsRestrictedUploads:true,createUploadAuthorization(){},verifyResource(){},createRestrictedPreview(){}};expect(adminProviderCompleteness({env:{ADMIN_ENVIRONMENT:'production',ADMIN_OWNER_DISCORD_ID:owner},data:{...data,adminCloudinaryProvider:restrictedProvider}}).restrictedUploads).toBe(true);expect(adminProviderCompleteness({env:{ADMIN_ENVIRONMENT:'preview',ADMIN_OWNER_DISCORD_ID:owner},data:{...data,adminCloudinaryProvider:restrictedProvider}}).restrictedUploads).toBe(false);
  });
  it('requires both signals, is idempotent, and synchronizes an associated upload',async()=>{const publications=createMemoryPublicationStore(),uploads=createMemoryUploadStore();await publications.create({publicationId:'pub-1',actorDiscordId:owner,action:'collection.update',status:'deployment_pending',commitSha:commit,catalogDigest,recoverable:true,createdAt:now.toISOString(),updatedAt:now.toISOString()});await uploads.create({jobId:'upload-1',actorDiscordId:owner,proposedAssetId:'nv-999',status:'deployment_pending',commitSha:commit,catalogDigest,recoverable:true,createdAt:now.toISOString(),updatedAt:now.toISOString(),expiresAt:'2026-08-07T00:00:00Z'});const verifier=createMockDeploymentVerifier({state:'live',deploymentState:'success',markerState:'matched',deploymentId:'deploy-1',deployedCommitSha:commit});const context={env:{},data:{publicationStore:publications,uploadStore:uploads,deploymentVerifier:verifier}},admin={discordId:owner,role:'owner'};expect((await verifyPublicationDeployment(context,{admin,publicationId:'pub-1',requestId:'request-1',now})).live).toBe(true);expect((await uploads.get('upload-1')).status).toBe('live');expect((await verifyPublicationDeployment(context,{admin,publicationId:'pub-1',requestId:'request-2',now})).live).toBe(true);expect(verifier.calls).toHaveLength(1);});
  it('keeps mismatches pending and maps terminal deployment failure',async()=>{for(const result of [{state:'pending',deploymentState:'success',markerState:'mismatch',failureCode:'catalog_marker_mismatch'},{state:'failed',deploymentState:'failed',failureCode:'deployment_failed'}]){const store=createMemoryPublicationStore();await store.create({publicationId:'pub',actorDiscordId:owner,action:'category.update',status:'deployment_pending',commitSha:commit,catalogDigest,recoverable:true,createdAt:now.toISOString(),updatedAt:now.toISOString()});const response=await verifyPublicationDeployment({env:{},data:{publicationStore:store,deploymentVerifier:createMockDeploymentVerifier(result)}},{admin:{discordId:owner,role:'owner'},publicationId:'pub',requestId:'request',now});expect(response.status).toBe(result.state==='pending'?'deployment_pending':'failed');}});
});

describe('Cloudflare deployment and marker verifier',()=>{
  it('uses the fixed production project and marker targets',()=>{expect(DEPLOYMENT_TARGET).toEqual({project:'neuevault',branch:'main',markerUrl:'https://www.pfseeker.com/catalog-version.json'});expect(createCloudflareDeploymentVerifier({env:{}})).toBeNull();});
  it('requires a successful matching deployment and exact live digest',async()=>{const calls=[];vi.stubGlobal('fetch',vi.fn(async url=>{calls.push(String(url));if(String(url).includes('api.cloudflare.com'))return new Response(JSON.stringify({success:true,result:[{id:'deploy-1',environment:'production',deployment_trigger:{metadata:{branch:'main',commit_hash:commit}},latest_stage:{status:'success'}}]}),{status:200,headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify({version:1,catalogDigest}),{status:200,headers:{'Content-Type':'application/json'}});}));const provider=createCloudflareDeploymentVerifier({env:{CLOUDFLARE_ACCOUNT_ID:'c'.repeat(32),CLOUDFLARE_PAGES_READ_TOKEN:'read-only-token-placeholder'}});await expect(provider.verify({commitSha:commit,catalogDigest})).resolves.toMatchObject({state:'live',deploymentId:'deploy-1',deployedCommitSha:commit});expect(calls[0]).toContain('/pages/projects/neuevault/deployments?env=production');expect(calls[1]).toContain('https://www.pfseeker.com/catalog-version.json?verify=');vi.unstubAllGlobals();});
  it('does not fetch the marker for queued, failed, or wrong-commit deployments',async()=>{for(const [status,expected] of [['building','pending'],['failure','failed']]){const fetcher=vi.fn(async()=>new Response(JSON.stringify({success:true,result:[{id:'deploy',environment:'production',deployment_trigger:{metadata:{branch:'main',commit_hash:commit}},latest_stage:{status}}]}),{status:200,headers:{'Content-Type':'application/json'}}));vi.stubGlobal('fetch',fetcher);const provider=createCloudflareDeploymentVerifier({env:{CLOUDFLARE_ACCOUNT_ID:'c'.repeat(32),CLOUDFLARE_PAGES_READ_TOKEN:'read-only-token-placeholder'}});expect((await provider.verify({commitSha:commit,catalogDigest})).state).toBe(expected);expect(fetcher).toHaveBeenCalledOnce();vi.unstubAllGlobals();}});
});
